---
# Hub
- ansible.builtin.include_tasks: hub.yml
  when: inventory_hostname in groups.beszel_hosts

- ansible.builtin.include_tasks: init.yml
  when: inventory_hostname in groups.beszel_hosts

- ansible.builtin.include_tasks: register.yml
  when: inventory_hostname in groups.beszel_hosts

- name: Register Beszel CNAME
  ansible.builtin.include_role:
    name: common
    tasks_from: register_cname
  vars:
    cname_name: "{{ beszel_cname }}.{{ lan_domain }}"
    cname_target: "{{ beszel_cname_target | default(inventory_hostname + '.' + lan_domain) }}"
  when: inventory_hostname in groups.beszel_hosts

# Agents
- ansible.builtin.include_tasks: agent.yml
  when: inventory_hostname in groups.beszel_agent_hosts
