---
- name: Deploy Beszel hub
  hosts: beszel_hosts
  become: true
  vars_files:
    - ../../vault/secrets.yml
  roles:
    - role: beszel

- name: Deploy Beszel agent
  hosts: beszel_agent_hosts
  become: true
  vars_files:
    - ../../vault/secrets.yml
  roles:
    - role: beszel_agent
