---
- name: Deploy Linkwarden
  hosts: linkwarden_hosts
  become: true
  vars_files:
    - ../../vault/secrets.yml
  pre_tasks:
    - ansible.builtin.set_fact:
        ca_ready: "{{ step_ca_root_cert_pem | length > 0 }}"
  roles:
    - role: linkwarden
      when: ca_ready
