---
- name: Deploy Linkwarden
  hosts: linkwarden_hosts
  become: true
  tags: [linkwarden]
  vars_files:
    - ../../vault/secrets.yml
  vars:
    postgres_port: 5432   # from roles/postgres/defaults/main.yml (SOT)
  roles:
    - role: linkwarden
