---
- name: Register {{ cname_name }} CNAME on router
  community.openwrt.uci:
    command: set
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "dhcp.{{ cname_name | regex_replace('[^a-zA-Z0-9_]', '_') }}", value: cname }
    - { key: "dhcp.{{ cname_name | regex_replace('[^a-zA-Z0-9_]', '_') }}.cname", value: "{{ cname_name }}" }
    - { key: "dhcp.{{ cname_name | regex_replace('[^a-zA-Z0-9_]', '_') }}.target", value: "{{ cname_target | default(inventory_hostname + '.' + lan_domain) }}" }
  delegate_to: "{{ groups['routers'][0] }}"

- name: Commit dhcp config on router
  community.openwrt.uci:
    command: commit
    key: dhcp
  delegate_to: "{{ groups['routers'][0] }}"

- name: Restart dnsmasq on router
  community.openwrt.command:
    cmd: /etc/init.d/dnsmasq restart
  delegate_to: "{{ groups['routers'][0] }}"
  changed_when: false
