# Portainer defaults

# Image
portainer_image_name: "portainer/portainer-ce"
portainer_image_tag: "2.39.2-alpine"

# Network
portainer_web_port: 9000
portainer_edge_port: 8000

# Paths
portainer_opt_dir: "{{ ansible_opt_base }}/portainer"
portainer_data_dir: "{{ docker_data_base }}/portainer"

# CNAME subdomain (without .{{ lan_domain }})
portainer_cname: "portainer"
