---
collections:
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.openwrt
    version: ">=1.2.0"
  - name: community.docker
  - name: community.postgresql

roles:
  - name: geerlingguy.security
