---
nvidia_gpu: true

system_optimize_mounts:
  - /
  - /mnt/reds
  - /mnt/green

# Beszel agent configuration
beszel_smart_devices:
  - /dev/sda:/dev/sda
  - /dev/sdb:/dev/sdb
  - /dev/sdc:/dev/sdc
  - /dev/sdd:/dev/sdd
  - /dev/nvme0n0:/dev/nvme0n0
beszel_smart_cap_add:
  - SYS_RAWIO
  - SYS_ADMIN
beszel_extra_volumes:
  - /mnt/reds/.beszel:/extra-filesystems/md0p1:ro
  - /mnt/green/.beszel:/extra-filesystems/sdd1:ro
