---
all:
  hosts:
    router:
      ansible_host: 10.10.10.1
      ansible_user: root
      ansible_ssh_pass: "{{ vault_router_ssh_pass }}"
      ansible_connection: ssh
      ansible_port: 22
    lab1:
      ansible_host: 10.10.10.10

  children:
    routers:
      hosts:
        router:

    servers:
      hosts:
        lab1:
      vars:
        ansible_python_interpreter: /usr/bin/python3

    docker_hosts:
      hosts:
        lab1:

    step_ca_hosts:
      hosts:
        lab1:
