# Traefik defaults

# Image
traefik_image_name: "traefik"
traefik_image_tag: "v3"

# Paths
traefik_data_dir: "{{ docker_data_base }}/traefik"  # acme.json (certs)
traefik_config_dir: "/opt/traefik"                  # dynamic config (our template)

# CNAME subdomain (without .{{ inventory_hostname }}.{{ lan_domain }})
traefik_cname: "traefik"

# Dependencies (synced with other roles, fallback here)
step_ca_port: 8443
