---
- name: Register step-ca CNAME on router
  ansible.builtin.include_role:
    name: common
    tasks_from: register_cname
  vars:
    cname_name: "step-ca.{{ lan_domain }}"
    cname_target: "{{ inventory_hostname }}.{{ lan_domain }}"
