# Beszel Agent defaults

# Image
beszel_agent_image_name: "henrygd/beszel-agent"
beszel_agent_image_tag: "alpine"
beszel_agent_image_nvidia_name: "henrygd/beszel-agent-nvidia"
beszel_agent_image_nvidia_tag: "latest"

# Paths
beszel_agent_opt_dir: "{{ ansible_opt_base }}/beszel-agent"
beszel_data_dir: "{{ docker_data_base }}/beszel-agent"

# CNAME subdomain (without .{{ lan_domain }})
beszel_agent_cname: "beszel"

# Network (hub connection)
beszel_port: 8090

# Agent settings
beszel_disk_cache: "1h"
