---
- ansible.builtin.include_tasks: deploy.yml
- name: Register inpx-web CNAME
  ansible.builtin.include_role:
    name: common
    tasks_from: register_cname
  vars:
    cname_name: "{{ inpx_web_cname_name | default('lib.' + lan_domain) }}"
    cname_target: "{{ inpx_web_cname_target | default(inventory_hostname + '.' + lan_domain) }}"
