---
admin_user: "{{ vault_admin_user }}"
admin_ssh_pubkey: "{{ vault_admin_ssh_pubkey }}"
ansible_user: "{{ admin_user }}"
ansible_become_password: "{{ vault_become_password }}"

# geerlingguy.security
security_ssh_port: 22
security_ssh_permit_root_login: "no"
security_ssh_password_authentication: "no"
security_ssh_x11_forwarding: "no"
security_ssh_allowed_users:
  - "{{ admin_user }}"
security_fail2ban_enabled: true
security_autoupdate_enabled: true
security_autoupdate_reboot: false

common_packages:
  - bash-completion
  - vim
  - nano
  - mc
  - bat
  - eza
  - lnav
  - htop
  - btop
  - smartmontools
  - nvme-cli
  - mdadm
  - git
  - jq
  - python3-dev
  - python3-pip
  - python3-venv
  - rsync
  - fzf
  - openssl

docker_users:
  - "{{ admin_user }}"

unattended_upgrades_enabled: true

# Traefik
traefik_acme_email: "admin@{{ lan_domain }}"
traefik_dashboard_user: "{{ vault_admin_user }}"
traefik_dashboard_password: "{{ vault_traefik_dashboard_password }}"

# step-ca
step_ca_port: 8443
step_ca_name: "Homelab CA"
step_ca_password: "{{ vault_step_ca_password }}"

# Portainer
portainer_admin_password: "{{ vault_portainer_admin_password }}"

# Vaultwarden
vaultwarden_admin_token: "{{ vault_vaultwarden_admin_token }}"

# qBittorrent
qbittorrent_password: "{{ vault_qbittorrent_password }}"

# Postgres
postgres_password: "{{ vault_postgres_password }}"

# Linkwarden
linkwarden_nextauth_secret: "{{ vault_linkwarden_nextauth_secret }}"
linkwarden_meili_master_key: "{{ vault_linkwarden_meili_master_key }}"
linkwarden_db_password: "{{ vault_linkwarden_db_password }}"

# Beszel
beszel_admin_email: "{{ vault_beszel_admin_email }}"
beszel_admin_password: "{{ vault_beszel_admin_password }}"
beszel_token: "{{ vault_beszel_token }}"
beszel_hub_key: "{{ vault_beszel_hub_key }}"
